# Generated by Django 3.2.9 on 2022-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='boards',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_count',
            field=models.IntegerField(),
        ),
    ]
