# Generated by Django 3.2.9 on 2022-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_match_has_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='to_guess',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
